CREATE TABLE ANIMAL (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR NOT NULL,
    FAMILY VARCHAR NOT NULL,
    SPECIE VARCHAR NOT NULL,
    WEIGHT DECIMAL NOT NULL
);

CREATE TABLE RESCUE (
    ID VARCHAR PRIMARY KEY,
    DATE VARCHAR NOT NULL,
    ANIMAL_ID INT NOT NULL,
    GA INT NOT NULL,
    LOCATION VARCHAR NOT NULL,
    FOREIGN KEY (ANIMAL_ID) REFERENCES ANIMAL(ID)
);

INSERT INTO ANIMAL (ID, NAME, FAMILY, SPECIE, WEIGHT) VALUES (1, 'Winnie', 'Cetaci', 'Dofí', 20.5);
INSERT INTO ANIMAL (ID, NAME, FAMILY, SPECIE, WEIGHT) VALUES (2, 'Berta', 'Tortuga Marina', 'Tortuga Boba', 10);
INSERT INTO ANIMAL (ID, NAME, FAMILY, SPECIE, WEIGHT) VALUES (3, 'William', 'Au Marina', 'Gavina', 5);

INSERT INTO RESCUE (ID, DATE, ANIMAL_ID, GA, LOCATION) VALUES ('RES-001', '2021-01-01', 2, 20, 'Barcelona');